"""Trains the queue-risk surrogate model (../volterra_ml/queue_risk.py) on the sweep dataset
generated by ../../simulation/examples/generate_queue_risk_dataset.jl, reports held-out MAE/R^2
per target (never blended into one score — see queue_risk.py's module docstring), and saves the
four trained LightGBM models to ../data/models/.

Run from ml/:
    python examples/train_queue_risk_model.py
"""

from __future__ import annotations

from volterra_ml.queue_risk import load_training_data, save_models, train_all_targets


def main() -> None:
    print("=" * 100)
    print("VOLTERRA Phase 6 — queue-risk surrogate model training")
    print("Labels are simulation/'s own validated M/G/c queueing model output, not real demand data.")
    print("=" * 100)

    df = load_training_data()
    print(f"\nLoaded {len(df)} training rows ({df['stall_count'].n_unique()} distinct stall counts, "
          f"temp_c range {df['temp_c'].min():.1f} to {df['temp_c'].max():.1f}).")

    models, evaluations = train_all_targets(df)

    print("\nHeld-out performance (20% random split, never seen during training):")
    for ev in evaluations:
        print(f"  {ev.target:20s}  MAE={ev.mae:.4f}  R^2={ev.r2:.4f}  (n_test={ev.n_test})")

    save_models(models)
    print(f"\nSaved 4 trained models to ml/data/models/. "
          f"Next: python examples/verify_real_sites.py")


if __name__ == "__main__":
    main()
